# Generated by Django 4.2.6 on 2023-10-23 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.IntegerField(choices=[(0, 'COD(Cash on delivery)'), (1, 'Credit Card'), (2, 'Debit Card'), (3, 'Paypal'), (4, 'Sofort by Klarna'), (5, 'Google Pay')], default=0)),
                ('acc_no', models.IntegerField(blank=True, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
