# Generated by Django 4.2.6 on 2023-10-25 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_product_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
