# Generated by Django 4.2.6 on 2023-10-25 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_product_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_discount',
            new_name='discount_name',
        ),
        migrations.AlterField(
            model_name='userpaymnet',
            name='acc_no',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
