# Generated by Django 4.2.6 on 2023-10-25 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_rename_product_discount_product_discount_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymnet',
            name='acc_no',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(24)]),
        ),
    ]
