# Generated by Django 4.2.6 on 2023-10-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_userpaymnet_acc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymnet',
            name='acc_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
