# Generated by Django 4.2.6 on 2023-10-25 18:09

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0012_alter_userpaymnet_acc_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmed_order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipment_via', models.IntegerField(choices=[(0, 'DHL'), (1, 'Hermes'), (3, 'DPD')], default=0)),
                ('order_status', models.CharField(default='Order Received', max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_confirmed_order', to=settings.AUTH_USER_MODEL), unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_confirmed_order', to=settings.AUTH_USER_MODEL)),
                ('user_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_payment_method', to='ecommerce.userpaymnet')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='cart_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('extra_info', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_product_info', to='ecommerce.product')),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
