# Generated by Django 4.2.6 on 2023-10-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_cart_items_extra_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmed_order_details',
            name='slug',
        ),
    ]
