# Generated by Django 4.2.6 on 2023-10-25 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_rename_cart_items_cartitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategories',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
