# Generated by Django 4.2.6 on 2023-11-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_remove_wishes_user_info_wishes_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishes',
            old_name='user_info',
            new_name='user',
        ),
    ]
