# Generated by Django 4.2.6 on 2023-11-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_alter_cartitems_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='extra_info',
            field=models.CharField(blank=True, default=False, max_length=250),
        ),
    ]
