# Generated by Django 4.2.6 on 2023-11-08 16:26

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_cartitems_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True),
        ),
    ]
