# Generated by Django 4.2.6 on 2023-11-08 17:53

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_remove_address_telephone_alter_address_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=phone_field.models.PhoneField(help_text='Contact mobile number', max_length=14, unique=True),
        ),
    ]
