# Generated by Django 4.2.6 on 2023-11-08 17:58

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_address_telephone_alter_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=phone_field.models.PhoneField(max_length=14, unique=True),
        ),
    ]
