# Generated by Django 4.2.6 on 2023-11-08 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0028_alter_address_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address_line_one', models.CharField(max_length=300)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('telephone', phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True)),
                ('mobile', phone_field.models.PhoneField(max_length=14, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='ConfirmedOrderDetails',
            new_name='ConfirmedOrderDetail',
        ),
        migrations.AlterModelOptions(
            name='wishes',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Wishes'},
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
