# Generated by Django 4.2.6 on 2023-11-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_shipmentdetail_rename_cartitems_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedorderdetail',
            name='user_payment',
        ),
        migrations.AddField(
            model_name='shipmentdetail',
            name='method',
            field=models.IntegerField(choices=[(0, 'COD(Cash on delivery)')], default=0),
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
