# Generated by Django 4.2.6 on 2023-11-09 19:04

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_remove_confirmedorderdetail_user_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetail',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
