# Generated by Django 4.2.6 on 2023-11-09 20:48

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_alter_shipmentdetail_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdetail',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='user', unique=True),
            preserve_default=False,
        ),
    ]
