# Generated by Django 4.2.6 on 2023-11-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_remove_shipmentdetail_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmedorderdetail',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='confirmedorderdetail',
            name='shipment_via',
        ),
        migrations.RemoveField(
            model_name='confirmedorderdetail',
            name='total',
        ),
        migrations.AddField(
            model_name='confirmedorderdetail',
            name='product_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='user_bought_product', to='ecommerce.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmedorderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='confirmedorderdetail',
            name='user_unique_order_no',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_info', to='ecommerce.product'),
        ),
        migrations.CreateModel(
            name='UserBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user_unique_order_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('shipment_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_shipment_info', to='ecommerce.product')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
