# Generated by Django 4.2.6 on 2023-11-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_alter_confirmedorderdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbill',
            name='shipment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_shipment_info', to='ecommerce.shipmentdetail'),
        ),
    ]
