# Generated by Django 4.2.6 on 2023-11-11 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0036_alter_confirmedorderdetail_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbill',
            name='user_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_bill_info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmedorderdetail',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bought_product', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='shipment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shipment_info', to='ecommerce.shipmentdetail'),
        ),
    ]
