# Generated by Django 4.2.6 on 2023-11-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_confirmedorderdetail_prod_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorderdetail',
            name='user_unique_order_no',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
