# Generated by Django 4.2.6 on 2023-11-16 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_alter_confirmedorderdetail_user_unique_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentdetail',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='mobile',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='postal_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
