# Generated by Django 4.2.6 on 2023-11-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_remove_shipmentdetail_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetail',
            name='mobile',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
