# Generated by Django 4.2.6 on 2023-11-18 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_alter_shipmentdetail_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
