# Generated by Django 4.2.6 on 2023-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_alter_confirmedorderdetail_quantity_delete_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetail',
            name='address_line_one',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='country',
            field=models.CharField(max_length=40),
        ),
    ]
