# Generated by Django 4.2.6 on 2023-12-05 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0043_alter_shipmentdetail_address_line_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetail',
            name='postal_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
