# Generated by Django 4.2.6 on 2023-12-05 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0044_alter_shipmentdetail_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetail',
            name='country',
            field=models.CharField(max_length=40, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
