# Generated by Django 4.2.6 on 2023-12-05 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0046_alter_shipmentdetail_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetail',
            name='mobile',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
